# Live Trading Configuration for Bank Nifty Options Trading System
# ⚠️ IMPORTANT: This is for LIVE TRADING with real money!
# Always test thoroughly in paper mode before using this configuration

# Trading mode - SET TO LIVE FOR REAL TRADING
mode: live

# Underlying symbol
underlying_symbol: BANKNIFTY

# API Configuration
api:
  credentials:
    # Use environment variables for security
    api_key: ${ANGEL_API_KEY}
    client_code: ${ANGEL_CLIENT_CODE}
    pin: ${ANGEL_PIN}
    totp_secret: ${ANGEL_TOTP_SECRET}
  
  # API settings
  base_url: https://apiconnect.angelbroking.com
  timeout: 30
  max_retries: 3
  retry_delay: 1.0
  rate_limit_calls: 90
  rate_limit_period: 60
  connection_pool_size: 10

# Risk Management Configuration - CONSERVATIVE SETTINGS FOR LIVE TRADING
risk:
  max_daily_loss: 5000.0        # Maximum loss per day (₹5,000)
  max_concurrent_trades: 2      # Conservative: Only 2 trades at once
  profit_target: 2000.0         # Profit target per trade (₹2,000)
  stop_loss: 1000.0            # Stop loss per trade (₹1,000)
  position_size_method: fixed
  max_position_size: 35        # Conservative position size (1 lot with current lot size)
  margin_buffer: 0.3           # 30% margin buffer
  daily_trade_limit: 5         # Maximum 5 trades per day
  emergency_stop_file: emergency_stop.txt

# Strategy Configuration - START WITH CONSERVATIVE STRADDLE ONLY
strategy:
  enabled_strategies:
    - straddle                 # Start with only straddle strategy
  
  evaluation_interval: 60      # Check every minute
  market_start_time: "09:15"
  market_end_time: "15:30"
  timezone: Asia/Kolkata
  
  # Conservative Straddle Strategy Settings
  straddle:
    enabled: true
    weight: 1.0
    min_confidence: 0.8        # High confidence threshold
    min_iv_rank: 0.7          # Only trade in high IV environment
    max_iv_rank: 0.95
    max_dte: 3                # Only same-day or next-day expiry
    min_volume: 500           # High liquidity requirement
    min_open_interest: 2000
    max_bid_ask_spread: 3.0   # Tight spreads only
    exit_time_minutes: 60     # Exit 1 hour before market close

# Logging Configuration
logging:
  level: INFO
  enable_console: true
  enable_file: true
  log_dir: logs
  log_file: live_trading.log
  max_file_size: 10485760     # 10MB
  backup_count: 30            # 30 days retention
  enable_json: true
  json_file: live_trading.json

# Notification Configuration - ENABLE FOR LIVE TRADING
notification:
  enabled: true
  types: [webhook]            # Add your preferred notification method
  
  # Webhook settings (replace with your webhook URL)
  webhook_url: ""             # Add your webhook URL here
  
  # Notification conditions
  notify_on_trade_entry: true
  notify_on_trade_exit: true
  notify_on_profit_target: true
  notify_on_stop_loss: true
  notify_on_daily_limit: true
  notify_on_error: true

# Additional Settings
data_cache_ttl: 300
position_check_interval: 30
emergency_stop_check_interval: 10