# Example Trading Configuration for Bank Nifty Options Trading System
# Copy this file to trading_config.yaml and customize as needed

# Trading mode: 'paper' for simulation, 'live' for actual trading
mode: paper

# Underlying symbol to trade
underlying_symbol: BANKNIFTY

# API Configuration
api:
  credentials:
    # Use environment variables for security
    api_key: ${ANGEL_API_KEY}
    client_code: ${ANGEL_CLIENT_CODE}
    pin: ${ANGEL_PIN}
    totp_secret: ${ANGEL_TOTP_SECRET}
  
  # API settings
  base_url: https://apiconnect.angelbroking.com
  timeout: 30
  max_retries: 3
  retry_delay: 1.0
  rate_limit_calls: 100
  rate_limit_period: 60
  connection_pool_size: 10

# Risk Management Configuration
risk:
  max_daily_loss: 5000.0
  max_concurrent_trades: 3
  profit_target: 2000.0
  stop_loss: 1000.0
  position_size_method: fixed
  margin_buffer: 0.2
  max_position_size: 100
  daily_trade_limit: 10
  emergency_stop_file: emergency_stop.txt

# Strategy Configuration
strategy:
  enabled_strategies:
    - straddle
    - directional
  
  evaluation_interval: 60
  market_start_time: "09:15"
  market_end_time: "15:30"
  timezone: Asia/Kolkata
  
  # Straddle Strategy Settings
  straddle:
    enabled: true
    weight: 1.0
    min_confidence: 0.6
    min_iv_rank: 0.5
    max_dte: 7
    min_volume: 100
    max_bid_ask_spread: 5.0
    exit_time_minutes: 30
  
  # Directional Strategy Settings
  directional:
    enabled: true
    weight: 0.8
    min_confidence: 0.7
    ema_period: 20
    atr_period: 14
    atr_multiplier: 2.0
    min_momentum: 0.02
  
  # Iron Condor Strategy Settings
  iron_condor:
    enabled: false
    weight: 0.6
    min_confidence: 0.5
    wing_distance: 200
    max_dte: 30
    target_delta: 0.15
    min_credit: 50.0
  
  # Greeks Strategy Settings
  greeks:
    enabled: false
    weight: 0.7
    min_confidence: 0.6
    target_delta: 0.3
    max_theta: -10.0
    min_vega: 5.0
    max_gamma: 0.01
  
  # Volatility Strategy Settings
  volatility:
    enabled: false
    weight: 0.5
    min_confidence: 0.6
    iv_percentile_threshold: 0.8
    min_iv_rank: 0.2
    volatility_lookback: 30

# Logging Configuration
logging:
  level: INFO
  log_dir: logs
  log_file: trading.log
  max_file_size: 10485760  # 10MB
  backup_count: 5
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S"
  enable_console: true
  enable_file: true
  enable_json: true
  json_file: trading.json

# Notification Configuration
notification:
  enabled: false
  types: []  # webhook, email, slack, telegram
  
  # Webhook settings
  webhook_url: ""
  
  # Email settings
  email_smtp_server: ""
  email_smtp_port: 587
  email_username: ""
  email_password: ${EMAIL_PASSWORD}
  email_to: []
  
  # Slack settings
  slack_webhook_url: ""
  
  # Telegram settings
  telegram_bot_token: ${TELEGRAM_BOT_TOKEN}
  telegram_chat_id: ""
  
  # Notification conditions
  notify_on_trade_entry: true
  notify_on_trade_exit: true
  notify_on_profit_target: true
  notify_on_stop_loss: true
  notify_on_daily_limit: true
  notify_on_error: true

# Backtesting Configuration
backtest:
  start_date: ""
  end_date: ""
  initial_capital: 100000.0
  commission_per_trade: 20.0
  slippage: 0.5
  data_source: angel_api
  output_dir: backtest_results
  generate_csv: true
  generate_json: true

# Additional Settings
data_cache_ttl: 300
position_check_interval: 30
emergency_stop_check_interval: 10